name: Storm CMS Content Type Base
description: Storm CMS Content Type Base
recipes:
  - core/recipes/tags_taxonomy
  - core/recipes/editorial_workflow
  - storm_cms_media
install:
  - link
  - options
  - text
  - auto_entitylabel
  - diff
  - field_group
  - inline_entity_form
  - metatag
  - metatag_open_graph
  - metatag_twitter_cards
  - metatag_views
  - quick_node_clone
  - type_tray
  - sam
  - scheduler
  - select2
config:
  import:
    node:
      - views.view.content
      - core.entity_view_mode.node.full
      - core.entity_view_mode.node.teaser
      - field.storage.node.body
      - system.action.node_delete_action
      - system.action.node_make_sticky_action
      - system.action.node_make_unsticky_action
      - system.action.node_promote_action
      - system.action.node_publish_action
      - system.action.node_save_action
      - system.action.node_unpromote_action
      - system.action.node_unpublish_action
    metatag:
      - metatag.metatag_defaults.node
      - metatag.metatag_defaults.global
      - metatag.metatag_defaults.403
      - metatag.metatag_defaults.404
      - metatag.metatag_defaults.front
      - metatag.settings
  actions:
      node.settings:
        simple_config_update:
          use_admin_theme: true
      scheduler.settings:
        simple_config_update:
          hide_seconds: true
