name: Storm CMS Content Type Base
description: Storm CMS Content Type Base
recipes:
  - core/recipes/tags_taxonomy
  - core/recipes/editorial_workflow
install:
  - link
  - media
  - node
  - options
  - text
  - diff
  - quick_node_clone
  - type_tray
  - scheduler
config:
  import:
    node:
      - views.view.content
      - core.entity_view_mode.node.full
      - core.entity_view_mode.node.teaser
      - field.storage.node.body
      - system.action.node_delete_action
      - system.action.node_make_sticky_action
      - system.action.node_make_unsticky_action
      - system.action.node_promote_action
      - system.action.node_publish_action
      - system.action.node_save_action
      - system.action.node_unpromote_action
      - system.action.node_unpublish_action
    metatag:
      - metatag.metatag_defaults.node
      - metatag.metatag_defaults.global
  actions:
      node.settings:
        simple_config_update:
          use_admin_theme: true
      scheduler.settings:
        simple_config_update:
          hide_seconds: true
